"""Add mesa_checkout_request_id to orders table

Revision ID: 007cab3603c2
Revises: 721d19682fe3
Create Date: 2025-12-20 11:53:28.222967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007cab3603c2'
down_revision = '721d19682fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesa_checkout_request_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('mesa_checkout_request_id')

    # ### end Alembic commands ###
