"""add mage url column

Revision ID: 721d19682fe3
Revises: e3316541ee94
Create Date: 2025-09-25 11:57:49.136176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721d19682fe3'
down_revision = 'e3316541ee94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
