"""add paid_at column to orders table

Revision ID: 7c765807b50b
Revises: fcb137ae9b99
Create Date: 2026-01-12 23:05:28.606503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c765807b50b'
down_revision = 'fcb137ae9b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.create_index('idx_orders_paid_at', ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_paid_at'), ['paid_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_paid_at'))
        batch_op.drop_index('idx_orders_paid_at')
        batch_op.drop_column('paid_at')

    # ### end Alembic commands ###
