"""add indexes and fix data integrity issues

Revision ID: fcb137ae9b99
Revises: 007cab3603c2
Create Date: 2026-01-12 22:51:40.534406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb137ae9b99'
down_revision = '007cab3603c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index('idx_cartitem_cart_product', ['cart_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_quantity'), ['quantity'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index('idx_cart_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_carts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_categories_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_categories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('idx_orderitem_order_product', ['order_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_quantity'), ['quantity'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('idx_order_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('idx_order_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_order_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_mpesa_checkout_request_id'), ['mesa_checkout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_total_amount'), ['total_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_product_category_price', ['category_id', 'price'], unique=False)
        batch_op.create_index('idx_product_category_stock', ['category_id', 'stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_stock'), ['stock'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_constraint('uq_users_phone_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.create_unique_constraint('uq_users_phone_number', ['phone_number'])
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_stock'))
        batch_op.drop_index(batch_op.f('ix_products_price'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index('idx_product_category_stock')
        batch_op.drop_index('idx_product_category_price')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_total_amount'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_mpesa_checkout_request_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))
        batch_op.drop_index('idx_order_user_status')
        batch_op.drop_index('idx_order_user_created')
        batch_op.drop_index('idx_order_status_created')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_quantity'))
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_price'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index('idx_orderitem_order_product')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
        batch_op.drop_index(batch_op.f('ix_categories_created_at'))
        batch_op.create_unique_constraint('uq_categories_name', ['name'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_user_id'))
        batch_op.drop_index(batch_op.f('ix_carts_created_at'))
        batch_op.drop_index('idx_cart_user_created')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_items_quantity'))
        batch_op.drop_index(batch_op.f('ix_cart_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_cart_items_cart_id'))
        batch_op.drop_index('idx_cartitem_cart_product')

    # ### end Alembic commands ###
